### ISSUE TITLE
Suggestion - Allow people to select custom folders for their alarm melodies.

### ISSUE THREAD

**Issue by Red6785** [vicolo-dev/chrono#14]
I have all my music in a custom folder, which is not automatically detected. Instead, it seems to be using the ringtone folder.

**Comment by AhsanSarwar45** [comment]
Hi, I have added the option to add custom melodies by going to Settings > General > Melodies. 

Although I didn't add the options to specify entire folders and automatically scan them. Changes and deletions in the folder might interfere with reliability of alarms ringing properly, And the added complexity doesn't seem worth it. 

That being said, you can still go to a folder and choose 'select all' in your file picker to add the entire folder's music as ringtones. Although I would caution that the app copies the audio files (due to reliability reasons), so adding hundreds of audio files would consume significant storage.

**Comment by Red6785** [comment]
Cheers. 👍
