### ISSUE TITLE
Desktop versions

### ISSUE THREAD

**Issue by trymeouteh** [vicolo-dev/chrono#171]
**Is your feature request related to a problem? Please describe.**
Unable to get app on Windows and Linux

**Describe the solution you'd like**
A version of the app for Windows and Linux, released as an EXE, AppImage, Scoop package, Winget package, Flatpak and NIX package.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by AhsanSarwar45** [comment]
Its an android-only app so it won't work on Windows and Linux. The alarm and timer features won't work there since Windows and Linux would require their own platform specific implementations for it to work (if they even support such an api). Unfortunately, I have no plans on supporting those platforms since the use-case for such an app on a desktop is very small. That being said, if anyone wants to work for support for any other platforms, contributions are welcome :)

**Comment by hgkamath** [comment]
- I wouldn't say the use-case is small, It would only be just as small as those android users who install a 3rd party open-source app as a replacement for the stock/vendor provided app. 
- AOTW, there seem to be no open-source modern replacements for the stock Win11 clock-app on WinOS or on any other equivalent DesktopOS. On Linux gnome-clock/Kclock are tied into their desktop-environment. On the other hard there are several opensource clock apps for Android, so I'm guessing the potential user base is fragmented. Admittedly, yours seems to be the only dart/flutter app with ongoing development, while others seem to have become abandoned or short term hobby projects.
- I thought that as chrono code is built with flutter/dart, the code would be platform agnostic.
- Perhaps you could point out, in a comment herein, the locations in code which are OS specific so that some future volunteer attempts a contribution.
