### ISSUE TITLE
Unable to set up auto-start

### ISSUE THREAD

**Issue by tkx3425** [vicolo-dev/chrono#223]
**Describe the bug**
On my Xiaomi phone, the alarm often doesn't ring. So I tried to turn on autostart. But when I click on the card, Chrono tells me "Auto start is not available for your device". What should I do?

**To Reproduce**
1. Go to 'settings'
2. Click on 'general'
3. Scroll down to 'reliability'
4. Click on 'auto start'
5. See error

**Expected behavior**
Enable auto-start smoothly

**Screenshots**
![Screenshot_2024-05-11-23-57-40-440_com vicolo chrono](https://github.com/vicolo-dev/chrono/assets/125032562/1bdbf004-eaad-4acd-b2a6-9ceae5c4f8fc)

![Screenshot_2024-05-11-23-57-31-501_com vicolo chrono](https://github.com/vicolo-dev/chrono/assets/125032562/0b39a8cf-5e1d-40ef-952a-52e9429fdaa8)

**Smartphone Information**
 - Device: Redmi Note 11 5G
 - OS: Hyper os,Android 13
 - App version 0.4.3

**Comment by AhsanSarwar45** [comment]
It just a message telling you that your device doesn't have autostart setting, so this setting doesn't apply to your device. Just to confirm though, try searching in your device settings for 'autostart' or 'background autostart'. If such a setting exists, let me know. If not, then you have nothing to worry about and alarm not ringing is being caused by other settings like battery optimizations etc. Try following the vendor specific guide for your MiUI version here: https://dontkillmyapp.com/xiaomi.

**Comment by tkx3425** [comment]
My device has an auto-start setting
![Screenshot_2024-05-12-12-10-55-104_com miui securitycenter](https://github.com/vicolo-dev/chrono/assets/125032562/df29ea28-adfc-4e72-8b2c-cdcfae892cc7)

**Comment by CloneWith** [comment]
> My device has an auto-launch setting but it doesn't work on Chrono

It's something with your OS version.
I'm using MIUI 14.0.10 and can use the card to the settings page.

![Auto-start setting page in Chinese](https://github.com/vicolo-dev/chrono/assets/110881926/ce7e0b80-506d-43c7-a4d2-506274aadf8c)

Above is the picture of the auto-start page working properly.

**Comment by tkx3425** [comment]
Autostart is turned on, but the alarm clock is delayed.
![Screenshot_2024-05-12-22-48-47-231_com miui securitycenter](https://github.com/vicolo-dev/chrono/assets/125032562/9893748a-178c-4abf-a2b5-77f0015501be)
