### ISSUE TITLE
Minor issues about style themes

### ISSUE THREAD

**Issue by CloneWith** [vicolo-dev/chrono#256]
**Description**
- The header text `Style Theme` seems untranslated.
- There is a 'Duplicate' entry in the dropdown menu, which won't work like the swipe action.

![Menu entry](https://github.com/vicolo-dev/chrono/assets/110881926/dfdc0b9f-8f92-44f8-83aa-8abc1b7698ae)

And could the style theme settings page always use swipe actions, regardless of the one defined in `General` (since no other tabs exist)?

**Smartphone Information**
 - Device: Redmi Note 12T Pro
 - OS: MIUI 14 @ Android 13
 - App version: 0.5.0-beta2

**Comment by AhsanSarwar45** [comment]
Thanks, this should be fixed in [v0.5.0-beta3](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta3). Let me know if you face any issues.

For the swipe actions, yes that's a good idea, but I will add that later after refactoring the swipe. You can create another enhancement issue for that.
