### ISSUE TITLE
One alarm doesn't go off (all others do)

### ISSUE THREAD

**Issue by gitthepie** [vicolo-dev/chrono#316]
**Describe the bug**
This bug causes certain alarms to not go off. Unfortunately, I've only seen the bug on one of the alarms, and I accidentally deleted it after it failed to go off multiple times in a row. But I will describe the behavior the best I can. I had the alarm clock set for two specific days in the week. The alarm was to go off only on those two days. However, the alarm wasn't going off. When the scheduled time was about 5 minutes past on one of these failed alarms, I glanced at my phone notifications and saw a message like "15 minutes until alarm". In other words, the alarm was already 5 minutes overdue, but still reported that it wasn't set to go off for another 15 minutes after the actually set time. I have double checked the alarm days of the week, hour, and minute, and all are correct.

**To Reproduce**
Reproducing this bug is extremely tricky, because it only happened to one of the alarms I'd set. Still, I will try my best.

1. Tap on the "Alarm" button on the bottom menu
2. Click the + symbol to add an alarm
3. Set a time
4. Click Customize
5. Set one of my music files as the melody.
6. Set the schedule type to "On Specified Week Days
7. Pick 2 of the days in the week for the alarm to go off
8. Click Save

**Expected behavior**
In roughly 4 out of my 5 alarms, setting an alarm in this fashion (though not for 2 days in the week and not for the buggy alarm's specific times) did cause the alarm to go off exactly at the scheduled time. But in one alarm, the alarm just wouldn't go off even when it was overdue.

**Screenshots**
I currently don't have screenshots of the problem, but I'm open to more testing if that will help reproduce the problem.

**Smartphone Information**
 - Device: Pixel 7
 - OS: Android version 14
 - App version: 0.5.1

**Additional context**
Unfortunately, I don't have much right now. What can I do to try to help reproduce the behavior?

**Comment by Shadeclan** [comment]
I have a similar but opposite issue - first and second alarms went off and I haven't been able to get another alarm to ring since.  

I have 9 different alarms spanning different day ranges and, of course, different times, some for a specific day, some for a day range and some for every day. All alarms are labeled,  I too chose a different alarm sound (Oxygen) for all alarms and set default sound to the same and vibration off as a default.  Snooze is set to 10 minute default. 3 tags were added and some default tags were deleted.  Date format display was changed to "d MMM yyyy".  Alarm upcoming lead time is 45 minutes. Changed Dismissed action to "Slide" although it had no effect.  Settings were backed up. All permissions have been granted except AutoStart is not available on my phone. 

Set the stock alarm to ring 2 minutes after the Chrono alarm as a precaution.

Please fix your app.  I've been searching for an alarm clock that does what your app does forever.

Phone: Motorola Moto One 5G Ace / Kiev / xt2113-2. 
OS: Lineage 20-20240714  (Android 13 equivalent)
App Version: 00.5.1

**Comment by azeem-io** [comment]
@gitthepie I think your specific issue might be the same as this #183, and is probably specific to Android 14 or some devices. The alarms that fail to go off might have been when the device was in a kind of doze or battery saving mode introduced in Android 14 or some device specific optimizations. Can you let me know if any other such alarm apps work properly on your device?

**Comment by Shadeclan** [comment]
> @gitthepie I think your specific issue might be the same as this #183, and is probably specific to Android 14 or some devices. The alarms that fail to go off might have been when the device was in a kind of doze or battery saving mode introduced in Android 14 or some device specific optimizations. Can you let me know if any other such alarm apps work properly on your device?

I have tried several different alarm apps on my phone and none of them, including the stock alarm, have this issue.  I made certain that Chrono was not battery optimized or snoozing in any way.  The issue occurs whether or not the phone is locked or even when the app itself is active.  

FYI: I don't know if this matters but all apps, including the stock phone app, have issues displaying an overlay screen on an unlocked phone in Android 13.  For example, when someone calls me while I'm using my phone, the overlay screen does not come up.  I have to go into the notifications area and choose the phone call - even bringing up the app may not give me access to the incoming call.  I have seriously considered regressing to Android 11 because of this issue.

**Comment by gitthepie** [comment]
> @gitthepie I think your specific issue might be the same as this #183, and is probably specific to Android 14 or some devices. The alarms that fail to go off might have been when the device was in a kind of doze or battery saving mode introduced in Android 14 or some device specific optimizations. Can you let me know if any other such alarm apps work properly on your device?

So far, Simple Clock (https://f-droid.org/en/packages/com.simplemobiletools.clock/) hasn't missed any alarms yet. I have version 5.11.2 of this app installed from either Google Play or F-Droid.

**Comment by AhsanSarwar45** [comment]
I found a case with something very similar to this (might have been the same issue), which I've fixed. Can you test [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1) to see if it fixes your issue?

**Comment by Shadeclan** [comment]
> I found a case with something very similar to this (might have been the same issue), which I've fixed. Can you test [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1) to see if it fixes your issue?
OK, I unfroze the earlier version of Chrono on my phone and updated it using the new ARM64 beta version.  
I will alter the alarms on the stock clock to go off 5 minutes after the Chrono alarms.
I am currently running the most recent version of LineageOS (21.0-20240922 Android 14 equivalent).
FYI: 1 version of LineageOS ago, there were issues with the stock alarms, forcing me to use my old alarm clock to get up in the morning.  This issue seems to be fixed in this latest version.

**Comment by AhsanSarwar45** [comment]
> Edit2: The 3 pm alarm went off but I was unable to dismiss it.  I wound up having to reboot my phone.  I'm going to have to refreeze the app until you can fix it.

Can you share the logs by going to Settings > Developer Options > App logs > Download button.

**Comment by Shadeclan** [comment]
> > Edit2: The 3 pm alarm went off but I was unable to dismiss it.  I wound up having to reboot my phone.  I'm going to have to refreeze the app until you can fix it.
> 
> Can you share the logs by going to Settings > Developer Options > App logs > Download button.

[chrono_logs_2024-09-23T17_16_33.txt](https://github.com/user-attachments/files/17104342/chrono_logs_2024-09-23T17_16_33.txt)

**Comment by AhsanSarwar45** [comment]
Closing this issue. The dismiss issue can be tracked here https://github.com/vicolo-dev/chrono/issues/323
