### ISSUE TITLE
It's new version(0.2.9) can't installed

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#42]
It's new version(0.2.9) can't installed on my device.

Play protect warns as unsafe app.
![Screenshot_20231217-130527](https://github.com/vicolo-dev/chrono/assets/65340361/6a187179-039a-40a1-9369-3df65aecfb43)

**Comment by AhsanSarwar45** [comment]
It can be installed, you just have to press the Install anyway button.

The reason it gives this warning is because I haven't published the app to Play Store, so it doesn't recognize it. As a workaround. I submit the new versions separately to Play Protect for review but that will take time after each new release.
